CREATE TABLE if NOT EXISTS rating(
	RAT_ID INT NOT NULL AUTO_INCREMENT ,
	ORD_ID INT NOT NULL,	 
	RAT_RATSTARS INT NOT NULL , 
	PRIMARY KEY(RAT_ID),
	FOREIGN KEY(ORD_ID) REFERENCES `order` (ORD_ID)
 
);